apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-conversao-temperatura
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-conversao-temperatura
  template:
    metadata:
      labels:
        app: api-conversao-temperatura
    spec:
      containers:
      - name: api-conversao-temperatura
        image: marciovsantos/api-conversao:1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api-conversao-temperatura
spec:
  selector:
    app: api-conversao-temperatura
  ports: 
  - port: 80
    protocol: TCP
    name: http
    nodePort: 30000
  type: NodePort